esphome:
  name: "rack-panel-leds"
  friendly_name: "rack-panel-leds"

esp32:
  board: esp32dev
  framework:
    type: arduino 

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome    
  # password: "your_ota_password"  # Optional but recommended

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #use_address: !secret rack-panel-leds-ip
  fast_connect: true    

  ap:
    ssid: "rack-panel-leds Fallback Hotspot"
    password: !secret wifi_password

captive_portal:
    
light:
  - platform: esp32_rmt_led_strip    
    id: led_strip
    name: "Test All LEDs"
    pin: GPIO16
    chipset: WS2812
    num_leds: 24
    rgb_order: GRB
    default_transition_length: 0s

    effects:
      # 1. Fast Alert Blink - critical errors
      - strobe:
          name: "Fast Blink"
          colors:
            - state: true
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              duration: 250ms
            - state: false
              duration: 250ms
      
      # 2. Slow Blink - warnings
      - strobe:
          name: "Slow Blink"
          colors:
            - state: true
              brightness: 100%
              duration: 1s
            - state: false
              duration: 1s
      
      # 3. Breathing - standby/idle
      - pulse:
          name: "Breathing"
          transition_length: 2s
          update_interval: 2s
          min_brightness: 10%
          max_brightness: 100%
      
      # 4. Fast Pulse - activity/processing
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.5s
          update_interval: 0.5s
      
      # 5. Flicker - degraded state
      - flicker:
          name: "Flicker"
          alpha: 95%
          intensity: 5%
      
      # 6. Rainbow - demo/test mode
      - addressable_rainbow:
          name: "Rainbow"
          speed: 10
          width: 50
      
      # 7. Color Wipe - startup sequence
      - addressable_color_wipe:
          name: "Color Wipe"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 1
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
      
      # 8. Scan/Knight Rider - scanning/searching
      - addressable_scan:
          name: "Scanner"
          move_interval: 100ms
          scan_width: 2
      
      # 9. Twinkle - random alerts
      - addressable_twinkle:
          name: "Twinkle"
          twinkle_probability: 5%
          progress_interval: 4ms
      
      # 10. Fireworks - celebration/success
      - addressable_fireworks:
          name: "Fireworks"
          update_interval: 32ms
          spark_probability: 10%
          use_random_color: true
          fade_out_rate: 120

  # Keep your partitions the same after this
  - platform: partition
    id: led_1
    name: "LED 1"
    segments:
      - id: led_strip
        from: 0
        to: 0  
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_2
    name: "LED 2"
    segments:
      - id: led_strip
        from: 3
        to: 3
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_3
    name: "LED 3"
    segments:
      - id: led_strip
        from: 4
        to: 4
    effects:
      - pulse:
          name: "Blink"        

  - platform: partition
    id: led_4
    name: "LED 4"
    segments:
      - id: led_strip
        from: 7
        to: 7
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_5
    name: "LED 5"
    segments:
      - id: led_strip
        from: 8
        to: 8
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_6
    name: "LED 6"
    segments:
      - id: led_strip
        from: 11
        to: 11    
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_7
    name: "LED 7"
    segments:
      - id: led_strip
        from: 12
        to: 12     
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_8
    name: "LED 8"
    segments:
      - id: led_strip
        from: 15
        to: 15
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_9
    name: "LED 9"
    segments:
      - id: led_strip
        from: 16
        to: 16
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_10
    name: "LED 10"
    segments:
      - id: led_strip
        from: 19
        to: 19
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_11
    name: "LED 11"
    segments:
      - id: led_strip
        from: 20
        to: 20
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_12
    name: "LED 12"
    segments:
      - id: led_strip
        from: 23
        to: 23
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_13
    name: "LED 13"
    segments:
      - id: led_strip
        from: 1
        to: 1
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_14
    name: "LED 14"
    segments:
      - id: led_strip
        from: 2
        to: 2
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_15
    name: "LED 15"
    segments:
      - id: led_strip
        from: 5
        to: 5
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_16
    name: "LED 16"
    segments:
      - id: led_strip
        from: 6
        to: 6
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_17
    name: "LED 17"
    segments:
      - id: led_strip
        from: 9
        to: 9
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_18
    name: "LED 18"
    segments:
      - id: led_strip
        from: 10
        to: 10
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_19
    name: "LED 19"
    segments:
      - id: led_strip
        from: 13
        to: 13
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_20
    name: "LED 20"
    segments:
      - id: led_strip
        from: 14
        to: 14
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_21
    name: "LED 21"
    segments:
      - id: led_strip
        from: 17
        to: 17
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_22
    name: "LED 22"
    segments:
      - id: led_strip
        from: 18
        to: 18
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_23
    name: "LED 23"
    segments:
      - id: led_strip
        from: 21
        to: 21
    effects:
      - pulse:
          name: "Blink"

  - platform: partition
    id: led_24
    name: "LED 24"
    segments:
      - id: led_strip
        from: 22
        to: 22
    effects:
      - pulse:
          name: "Blink"        
